/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AlertTip: typeof import('./src/components/common/AlertTip.vue')['default']
    AvatarUploader: typeof import('./src/components/common/AvatarUploader.vue')['default']
    ContentMobile: typeof import('./src/components/common/mobile/ContentMobile.vue')['default']
    ContentPC: typeof import('./src/components/common/pc/ContentPC.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    FooterMobile: typeof import('./src/components/common/mobile/FooterMobile.vue')['default']
    FooterPC: typeof import('./src/components/common/pc/FooterPC.vue')['default']
    HeaderMobile: typeof import('./src/components/common/mobile/HeaderMobile.vue')['default']
    HeaderMobileNav: typeof import('./src/components/common/mobile/HeaderMobileNav.vue')['default']
    HeaderPC: typeof import('./src/components/common/pc/HeaderPC.vue')['default']
    HeaderPCNav: typeof import('./src/components/common/pc/HeaderPCNav.vue')['default']
    InitialAvatar: typeof import('./src/components/common/InitialAvatar.vue')['default']
    LoginPage: typeof import('./src/components/common/LoginPage.vue')['default']
    RegisterPage: typeof import('./src/components/common/RegisterPage.vue')['default']
    ResetPassword: typeof import('./src/components/common/ResetPassword.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SlideVerify: typeof import('./src/components/common/SlideVerify.vue')['default']
    UserInfoMobile: typeof import('./src/components/common/mobile/UserInfoMobile.vue')['default']
    UserInfoPC: typeof import('./src/components/common/pc/UserInfoPC.vue')['default']
  }
}
