/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AlertTip: typeof import('./src/components/common/AlertTip.vue')['default']
    ContentMobile: typeof import('./src/components/common/mobile/ContentMobile.vue')['default']
    ContentPC: typeof import('./src/components/common/pc/ContentPC.vue')['default']
    copy: typeof import('./src/components/common/RegisterPage copy.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    FooterMobile: typeof import('./src/components/common/mobile/FooterMobile.vue')['default']
    FooterPC: typeof import('./src/components/common/pc/FooterPC.vue')['default']
    HeaderMobile: typeof import('./src/components/common/mobile/HeaderMobile.vue')['default']
    HeaderMobileNav: typeof import('./src/components/common/mobile/HeaderMobileNav.vue')['default']
    HeaderPC: typeof import('./src/components/common/pc/HeaderPC.vue')['default']
    HeaderPCNav: typeof import('./src/components/common/pc/HeaderPCNav.vue')['default']
    LoginMobile: typeof import('./src/components/common/mobile/LoginMobile.vue')['default']
    LoginPage: typeof import('./src/components/common/LoginPage.vue')['default']
    LoginPC: typeof import('./src/components/common/pc/LoginPC.vue')['default']
    Message: typeof import('./src/components/common/Message.vue')['default']
    Messege: typeof import('./src/components/common/messege.vue')['default']
    RegisterPage: typeof import('./src/components/common/RegisterPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SlideVerify: typeof import('./src/components/common/SlideVerify.vue')['default']
  }
}
