/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AlertTip: typeof import('./src/components/common/AlertTip.vue')['default']
    AvatarUploader: typeof import('./src/components/common/AvatarUploader.vue')['default']
    BindEmailDialog: typeof import('./src/components/common/BindEmailDialog.vue')['default']
    CarouselPC: typeof import('./src/components/pc/content/main/CarouselPC.vue')['default']
    CarouselPhone: typeof import('./src/components/phone/content/main/CarouselPhone.vue')['default']
    CommentPC: typeof import('./src/components/pc/userinfo/CommentPC.vue')['default']
    CommentPhone: typeof import('./src/components/phone/userinfo/CommentPhone.vue')['default']
    ContentPC: typeof import('./src/components/pc/content/ContentPC.vue')['default']
    ContentPhone: typeof import('./src/components/phone/content/ContentPhone.vue')['default']
    copy: typeof import('./src/components/common/editor/Editor copy.vue')['default']
    Editor: typeof import('./src/components/common/editor/Editor.vue')['default']
    'Editor copy': typeof import('./src/components/common/editor/Editor copy.vue')['default']
    ElImageViewer: typeof import('element-plus/es')['ElImageViewer']
    FavoritePC: typeof import('./src/components/pc/userinfo/FavoritePC.vue')['default']
    FavoritePhone: typeof import('./src/components/phone/userinfo/FavoritePhone.vue')['default']
    FooterPC: typeof import('./src/components/pc/FooterPC.vue')['default']
    FooterPhone: typeof import('./src/components/phone/FooterPhone.vue')['default']
    HeaderNavPC: typeof import('./src/components/pc/HeaderNavPC.vue')['default']
    HeaderNavPhone: typeof import('./src/components/phone/HeaderNavPhone.vue')['default']
    HeaderPC: typeof import('./src/components/pc/HeaderPC.vue')['default']
    HeaderPhone: typeof import('./src/components/phone/HeaderPhone.vue')['default']
    HotPostsPC: typeof import('./src/components/pc/content/aside/HotPostsPC.vue')['default']
    Icon: typeof import('./src/components/common/icons/Icon.vue')['default']
    IndexUserInfoPC: typeof import('./src/components/pc/userinfo/IndexUserInfoPC.vue')['default']
    IndexUserInfoPhone: typeof import('./src/components/phone/userinfo/IndexUserInfoPhone.vue')['default']
    InfoPC: typeof import('./src/components/pc/userinfo/InfoPC.vue')['default']
    InfoPhone: typeof import('./src/components/phone/userinfo/InfoPhone.vue')['default']
    InitialAvatar: typeof import('./src/components/common/InitialAvatar.vue')['default']
    MonthArchivePC: typeof import('./src/components/pc/content/aside/MonthArchivePC.vue')['default']
    OrderPC: typeof import('./src/components/pc/userinfo/OrderPC.vue')['default']
    OrderPhone: typeof import('./src/components/phone/userinfo/OrderPhone.vue')['default']
    PostItemAside: typeof import('./src/components/common/base/PostItemAside.vue')['default']
    PostItemMain: typeof import('./src/components/common/base/PostItemMain.vue')['default']
    PostListPC: typeof import('./src/components/pc/content/main/PostListPC.vue')['default']
    PostListPhone: typeof import('./src/components/phone/content/main/PostListPhone.vue')['default']
    PostPC: typeof import('./src/components/pc/userinfo/PostPC.vue')['default']
    PostPhone: typeof import('./src/components/phone/userinfo/PostPhone.vue')['default']
    RecommendedReadsPC: typeof import('./src/components/pc/content/aside/RecommendedReadsPC.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SlideVerify: typeof import('./src/components/common/SlideVerify.vue')['default']
    TagItem: typeof import('./src/components/common/base/TagItem.vue')['default']
    TagsPC: typeof import('./src/components/pc/content/aside/TagsPC.vue')['default']
    UserDropdownPC: typeof import('./src/components/pc/UserDropdownPC.vue')['default']
    VipPC: typeof import('./src/components/pc/userinfo/VipPC.vue')['default']
    VipPhone: typeof import('./src/components/phone/userinfo/VipPhone.vue')['default']
  }
}
