worker_processes  1; # 设置工作进程数

events {
    worker_connections  1024; # 设置每个工作进程的最大连接数
}

http {
    include       mime.types; # 包含 mime.types 文件
    default_type  application/octet-stream; # 设置默认文件类型

    sendfile        on; # 开启 sendfile
    keepalive_timeout  120; # 设置 keepalive 超时时间 65 秒

    gzip  on; # 开启 gzip 压缩
    client_max_body_size 100M; # 增加此行，设置上传文件大小限制为100MB

    # 配置服务器
    server { # 服务器块
        listen       80; # 监听端口
        server_name  jiaopengzi.com; # 设置服务器名称
        charset utf-8; # 设置编码

        location / { # 配置根目录
            return 301 https://$host$request_uri; # 将所有 HTTP 请求重定向到 HTTPS
        }
    }

    server { # HTTPS 服务器块
        listen       443 ssl; # 监听端口，开启 SSL
        server_name  jiaopengzi.com; # 设置服务器名称
        charset utf-8; # 设置编码

        ssl_certificate /etc/nginx/ssl/jiaopengzi.com.pem; # SSL 证书路径
        ssl_certificate_key /etc/nginx/ssl/jiaopengzi.com.key; # SSL 证书密钥路径

        location / { # 配置根目录
            root   /usr/share/nginx/html; # 设置静态文件目录
            index  index.html index.htm; # 设置默认索引文件
            try_files $uri $uri/ /index.html; # 在找不到请求的资源时返回单页应用的入口 HTML 文件
        }

        location /api/ { # 配置 api 代理
            proxy_pass http://blog-server:8080/api/; # 使用 docker 服务名称 docker自定义网络
            proxy_http_version 1.1; # 设置 HTTP 版本
            proxy_set_header Upgrade $http_upgrade; # 设置升级头
            proxy_set_header Connection "upgrade"; # 设置连接头
            proxy_set_header Host $host; # 设置主机头
            proxy_set_header X-Real-IP $remote_addr; # 设置真实 IP 头
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; # 设置转发头
        }
    }
}
