worker_processes 1; # 设置工作进程数

pid /tmp/nginx.pid;  # 在镜像中确保有权限写入 nginx.pid

events {
    worker_connections 1024; # 设置每个工作进程的最大连接数
}

http {
    include mime.types; # 包含 mime.types 文件
    default_type application/octet-stream; # 设置默认文件类型

    sendfile on; # 开启 sendfile
    keepalive_timeout 120; # 设置 keepalive 超时时间 65 秒

    gzip on; # 开启 gzip 压缩
    gzip_min_length 10240; # 设置最小压缩文件大小为 10KB
    gzip_buffers 4 16k; # 设置 gzip 缓冲区大小
    gzip_types text/plain application/javascript application/x-javascript text/javascript text/css application/xml; # 设置需要压缩的文件类型
    gzip_static on; # 如果存在预压缩的 .gz 文件，则直接提供该文件
    client_max_body_size 100M; # 设置上传文件大小限制为100MB

    # 配置服务器
    server {
        listen 80; # 监听端口
        server_name dev.jiaopengzi.com; # 设置服务器名称
        charset utf-8; # 设置编码

        location / {
            root /usr/share/nginx/html; # 设置静态文件目录
            index index.html index.htm; # 设置默认索引文件
            try_files $uri $uri/ /index.html; # 在找不到请求的资源时返回单页应用的入口 HTML 文件
        }

        location /api/ {
            proxy_pass http://blog-server:5426/api/; # 使用 docker 服务名称 docker自定义网络(不在同一自定义网络下需要更换为宿主内网ip)
            proxy_http_version 1.1; # 设置 HTTP 版本
            proxy_set_header Upgrade $http_upgrade; # 设置升级头
            proxy_set_header Connection "upgrade"; # 设置连接头
            proxy_set_header Host $host; # 设置主机头
            proxy_set_header X-Real-IP $remote_addr; # 设置真实 IP 头
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; # 设置转发头
            proxy_read_timeout 600; # 设置代理读取超时时间
            proxy_connect_timeout 600; # 设置代理连接超时时间
            proxy_send_timeout 600; # 设置代理发送超时时间
        }
        
        # https://raw.githubusercontent.com/jiaopengzi/blog-server/refs/heads/main/CHANGELOG.md
        # https://gitee.com/jiaopengzi/blog-server/raw/main/CHANGELOG.md
        
        # GitHub raw 代理
        location /admin/raw-github/ {
            proxy_pass https://raw.githubusercontent.com/;  # 注意结尾的 /
            proxy_set_header Host raw.githubusercontent.com;
            proxy_ssl_server_name on;  # 必须开启, 否则 SNI 可能失败
            proxy_redirect off;
        }

        # Gitee raw 代理
        location /admin/raw-gitee/ {
            proxy_pass https://gitee.com/;  # 注意结尾的 /
            proxy_set_header Host gitee.com;
            proxy_ssl_server_name on;
            proxy_redirect off;
        }
    }
}
